CREATE SEQUENCE IF NOT EXISTS data_sequence START 1 INCREMENT 1;

CREATE TABLE IF NOT EXISTS dataserver (
  id INTEGER NOT NULL PRIMARY KEY DEFAULT nextval('data_sequence'),
  guid VARCHAR(255) NOT NULL,
  insertedon TIMESTAMP NOT NULL DEFAULT NOW(),
  migratedon TIMESTAMP NOT NULL DEFAULT NOW()
);
